#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:cn/rzedu/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.rzedu.**.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID", 2:"全局唯一ID(数字类型唯一ID)", 3:"全局唯一ID UUID"
      id-type:0

#swagger扫描路径配置
swagger:
  base-packages:
  - cn.rzedu

#feign配置
#feign:
#  hystrix:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false

#hystrix配置
#hystrix:
#  threadpool:
#    default:
#      coreSize: 300
#      maxQueueSize: 1000
#      queueSizeRejectionThreshold: 800
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000