#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:cn/rzedu/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.rzedu.**.entity

#swagger扫描路径配置
swagger:
  base-packages:
  - cn.rzedu
